


#1 Question 1, Guess a number generated by the computer

import random

def guess(x):
    random_number = random.randint(1, x)
    guess = 0
    while guess != random_number:
        guess = int( input("Enter a number betwwen 1 and {0}: ".format(x)) )

        if guess > random_number:
            print("too high")
        elif guess < random_number: 
            print("too low")
        
    print("congrates   Correct !!")


guess(100)